;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-or-skip-quote
	evil-insert
	evil-next-line
	evil-normal-state
	evil-previous-line
	evil-search-word-forward
	evil-yank
	))

(setq mc/cmds-to-run-once
      '(
	))
